version: '3'

services:
  app:
    build: .
    ports:
      - "2007:8081"
#    networks:
 #     products-net:
  #      ipv4_address: 172.19.0.90
    restart: always
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - championsworld

networks:
  championsworld:
    external: true
